---
- name: Install PostgreSQL Stack (PostgreSQL 18 + PostgREST + pgweb + Authelia)
  hosts: all
  become: true
  vars:
    install_dir: "{{ install_dir | default('/opt/postgresql-stack') }}"
    data_dir: "{{ install_dir }}/data"
    postgres_port: "{{ postgres_port | default(5432) }}"
    postgrest_port: "{{ postgrest_port | default(3000) }}"
    pgweb_port: "{{ pgweb_port | default(8081) }}"
    authelia_port: "{{ authelia_port | default(9091) }}"
    auth_port: "{{ auth_port | default(5000) }}"
    postgres_db: "{{ postgres_db | default('postgres') }}"
    postgres_user: "{{ postgres_user | default('postgres') }}"
    postgrest_role: "{{ postgrest_role | default('authenticator') }}"
    postgrest_anon_role: "{{ postgrest_anon_role | default('anon') }}"
    enable_ssl: "{{ enable_ssl | default(true) }}"
    # Path-based routing - all services under one domain
    pgweb_path: "/pgweb"
    postgrest_path: "/postgrest"
    auth_path: "/auth"
    authelia_path: "/authelia"

  tasks:
    - name: Validate required variables
      ansible.builtin.assert:
        that:
          - domain is defined
          - domain | length > 0
          - enable_ssl == false or (admin_email is defined and admin_email | length > 0)
        fail_msg: "Missing required variables. domain is required. admin_email is required when enable_ssl is true."

    - name: Generate PostgreSQL password if not provided
      ansible.builtin.set_fact:
        postgres_password: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}"
      when: postgres_password is not defined or postgres_password | length == 0

    - name: Generate PostgREST authenticator password if not provided
      ansible.builtin.set_fact:
        postgrest_password: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}"
      when: postgrest_password is not defined or postgrest_password | length == 0

    - name: Generate PostgREST JWT secret if not provided
      ansible.builtin.set_fact:
        postgrest_jwt_secret: "{{ lookup('password', '/dev/null length=64 chars=ascii_letters,digits') }}"
      when: postgrest_jwt_secret is not defined or postgrest_jwt_secret | length == 0

    - name: Generate Authelia JWT secret if not provided
      ansible.builtin.set_fact:
        authelia_jwt_secret: "{{ lookup('password', '/dev/null length=64 chars=ascii_letters,digits') }}"
      when: authelia_jwt_secret is not defined or authelia_jwt_secret | length == 0

    - name: Generate Authelia session secret if not provided
      ansible.builtin.set_fact:
        authelia_session_secret: "{{ lookup('password', '/dev/null length=64 chars=ascii_letters,digits') }}"
      when: authelia_session_secret is not defined or authelia_session_secret | length == 0

    - name: Generate Authelia storage encryption key if not provided
      ansible.builtin.set_fact:
        authelia_storage_encryption_key: "{{ lookup('password', '/dev/null length=64 chars=ascii_letters,digits') }}"
      when: authelia_storage_encryption_key is not defined or authelia_storage_encryption_key | length == 0

    - name: Generate Authelia admin password if not provided
      ansible.builtin.set_fact:
        authelia_admin_password: "{{ lookup('password', '/dev/null length=24 chars=ascii_letters,digits') }}"
      when: authelia_admin_password is not defined or authelia_admin_password | length == 0

    - name: Generate API user password if not provided
      ansible.builtin.set_fact:
        api_user_password: "{{ lookup('password', '/dev/null length=24 chars=ascii_letters,digits') }}"
      when: api_user_password is not defined or api_user_password | length == 0

    - name: Generate API admin password if not provided
      ansible.builtin.set_fact:
        api_admin_password: "{{ lookup('password', '/dev/null length=24 chars=ascii_letters,digits') }}"
      when: api_admin_password is not defined or api_admin_password | length == 0

    # Nginx Detection Logic
    - name: Check if system Nginx is installed
      ansible.builtin.command: which nginx
      register: nginx_binary
      failed_when: false
      changed_when: false

    - name: Check if ports 80 and 443 are in use
      ansible.builtin.shell: |
        set -o pipefail
        port80=$(ss -tuln | grep ':80 ' || echo "free")
        port443=$(ss -tuln | grep ':443 ' || echo "free")
        if [[ "$port80" != "free" ]] || [[ "$port443" != "free" ]]; then
          echo "in_use"
        else
          echo "free"
        fi
      register: ports_check
      changed_when: false

    - name: Fail if ports are occupied and Nginx is not installed
      ansible.builtin.fail:
        msg: |
          ERROR: Ports 80 and/or 443 are already in use, but Nginx is not installed.

          This playbook uses system Nginx for multi-app support.
          Options:
          1. Free up ports 80/443 and re-run (playbook will install system Nginx)
          2. Install Nginx manually first
      when:
        - nginx_binary.rc != 0
        - ports_check.stdout == 'in_use'

    - name: Display Nginx deployment decision
      ansible.builtin.debug:
        msg:
          - "Deploying PostgreSQL Stack with system Nginx + Certbot SSL"
          - "{{ 'Will use existing Nginx installation' if nginx_binary.rc == 0 else 'Will install Nginx from distribution repository' }}"
          - "SSL: Automatic via Certbot"

    - name: Install required packages
      ansible.builtin.package:
        name:
          - curl
          - ca-certificates
          - gnupg
          - openssl
        state: present

    - name: Check if Docker is installed
      ansible.builtin.command: docker --version
      register: docker_installed
      failed_when: false
      changed_when: false

    - name: Install Docker (Debian/Ubuntu)
      block:
        - name: Add Docker GPG key
          ansible.builtin.apt_key:
            url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
            state: present

        - name: Add Docker repository
          ansible.builtin.apt_repository:
            repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
            state: present

        - name: Install Docker packages
          ansible.builtin.apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-compose-plugin
            state: present
            update_cache: true
      when:
        - docker_installed.rc != 0
        - ansible_os_family == "Debian"

    - name: Install Docker (RHEL/CentOS/Rocky/Alma)
      block:
        - name: Add Docker repository
          ansible.builtin.yum_repository:
            name: docker-ce
            description: Docker CE Stable
            baseurl: "https://download.docker.com/linux/{{ 'centos' if ansible_distribution == 'CentOS' else 'rhel' if ansible_distribution in ['RedHat', 'OracleLinux'] else ansible_distribution | lower }}/{{ ansible_distribution_major_version }}/$basearch/stable"
            gpgcheck: true
            gpgkey: "https://download.docker.com/linux/{{ 'centos' if ansible_distribution == 'CentOS' else 'rhel' if ansible_distribution in ['RedHat', 'OracleLinux'] else ansible_distribution | lower }}/gpg"
            enabled: true

        - name: Install Docker packages
          ansible.builtin.dnf:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-compose-plugin
            state: present
      when:
        - docker_installed.rc != 0
        - ansible_os_family == "RedHat"

    - name: Start and enable Docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true

    - name: Hash Authelia admin password
      ansible.builtin.shell: docker run --rm authelia/authelia:4.38.16 authelia crypto hash generate argon2 --password "{{ authelia_admin_password }}" | grep 'Digest:' | awk '{print $2}'
      register: authelia_password_hash_result
      changed_when: false

    - name: Set Authelia admin password hash
      ansible.builtin.set_fact:
        authelia_admin_password_hash: "{{ authelia_password_hash_result.stdout }}"

    - name: Create installation directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ install_dir }}"
        - "{{ data_dir }}"
        - "{{ data_dir }}/postgres"
        - "{{ data_dir }}/authelia"

    - name: Create .env file
      ansible.builtin.template:
        src: templates/env.j2
        dest: "{{ install_dir }}/.env"
        mode: '0600'

    - name: Create compose.yml
      ansible.builtin.template:
        src: templates/compose.yml.j2
        dest: "{{ install_dir }}/compose.yml"
        mode: '0644'

    - name: Create PostgREST configuration
      ansible.builtin.template:
        src: templates/postgrest.conf.j2
        dest: "{{ install_dir }}/postgrest.conf"
        mode: '0644'

    - name: Create Authelia configuration
      ansible.builtin.template:
        src: templates/authelia-config.yml.j2
        dest: "{{ install_dir }}/authelia-config.yml"
        mode: '0600'

    - name: Create Authelia users database
      ansible.builtin.template:
        src: templates/authelia-users.yml.j2
        dest: "{{ install_dir }}/authelia-users.yml"
        mode: '0600'

    - name: Create PostgreSQL init script
      ansible.builtin.template:
        src: templates/init-postgrest.sql.j2
        dest: "{{ install_dir }}/init-postgrest.sql"
        mode: '0644'

    - name: Create Auth service Python script
      ansible.builtin.template:
        src: templates/auth-service.py.j2
        dest: "{{ install_dir }}/auth-service.py"
        mode: '0755'

    - name: Create Auth service requirements file
      ansible.builtin.template:
        src: templates/auth-requirements.txt.j2
        dest: "{{ install_dir }}/auth-requirements.txt"
        mode: '0644'

    - name: Create Auth service Dockerfile
      ansible.builtin.template:
        src: templates/Dockerfile.auth.j2
        dest: "{{ install_dir }}/Dockerfile.auth"
        mode: '0644'

    # System Nginx Mode - Install or use existing Nginx installation
    - name: Check if system Nginx is already installed
      ansible.builtin.command: which nginx
      register: system_nginx_check
      failed_when: false
      changed_when: false

    - name: Install Nginx (Debian/Ubuntu)
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true
      when:
        - system_nginx_check.rc != 0
        - ansible_os_family == "Debian"

    - name: Install Nginx (RHEL/CentOS/Rocky/Alma)
      ansible.builtin.dnf:
        name: nginx
        state: present
      when:
        - system_nginx_check.rc != 0
        - ansible_os_family == "RedHat"

    - name: Start and enable Nginx service
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: true

    - name: Create initial HTTP Nginx configuration (for Certbot validation)
      ansible.builtin.template:
        src: "templates/nginx-http-postgresql-stack.conf.j2"
        dest: "/etc/nginx/sites-available/postgresql-stack"
        mode: '0644'
      when: ansible_os_family == "Debian"

    - name: Create initial HTTP Nginx configuration (for Certbot validation) - RHEL
      ansible.builtin.template:
        src: "templates/nginx-http-postgresql-stack.conf.j2"
        dest: "/etc/nginx/conf.d/postgresql-stack.conf"
        mode: '0644'
      when: ansible_os_family == "RedHat"

    - name: Enable Nginx site (Debian/Ubuntu)
      ansible.builtin.file:
        src: "/etc/nginx/sites-available/postgresql-stack"
        dest: "/etc/nginx/sites-enabled/postgresql-stack"
        state: link
      when: ansible_os_family == "Debian"
      notify: Reload Nginx

    - name: Test Nginx configuration
      ansible.builtin.command: nginx -t
      changed_when: false

    - name: Reload Nginx
      ansible.builtin.systemd:
        name: nginx
        state: reloaded

    - name: Pull Docker images
      ansible.builtin.command: docker compose pull
      args:
        chdir: "{{ install_dir }}"
      register: docker_pull
      changed_when: "'Downloaded' in docker_pull.stderr or 'Pulled' in docker_pull.stderr"

    - name: Start PostgreSQL Stack services
      ansible.builtin.command: docker compose up -d
      args:
        chdir: "{{ install_dir }}"
      register: docker_up
      changed_when: "'Started' in docker_up.stderr or 'Created' in docker_up.stderr"

    - name: Wait for PostgreSQL to be ready
      ansible.builtin.shell: docker exec postgresql-stack-db pg_isready
      changed_when: false -U {{ postgres_user }}
      register: result
      until: result.rc == 0
      retries: 30
      delay: 5

    - name: Initialize PostgREST roles in database
      ansible.builtin.shell: docker exec -i postgresql-stack-db psql -U {{ postgres_user }} -d {{ postgres_db }} < {{ install_dir }}/init-postgrest.sql
      register: init_result
      changed_when: "'CREATE ROLE' in init_result.stdout"

    - name: Wait for PostgREST to be ready
      ansible.builtin.uri:
        url: "http://localhost:{{ postgrest_port }}"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 30
      delay: 5

    - name: Wait for pgweb to be ready
      ansible.builtin.uri:
        url: "http://localhost:{{ pgweb_port }}"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 30
      delay: 5

    - name: Wait for Authelia to be ready
      ansible.builtin.uri:
        url: "http://localhost:{{ authelia_port }}/api/health"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 30
      delay: 5

    - name: Wait for Auth service to be ready
      ansible.builtin.uri:
        url: "http://localhost:{{ auth_port }}/health"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 30
      delay: 5

    # SSL Certificate with Certbot
    - name: Install Certbot (Debian/Ubuntu)
      ansible.builtin.apt:
        name:
          - certbot
          - python3-certbot-nginx
        state: present
      when:
        - enable_ssl
        - ansible_os_family == "Debian"

    - name: Install Certbot (RHEL/Rocky/Alma)
      ansible.builtin.dnf:
        name:
          - certbot
          - python3-certbot-nginx
        state: present
      when:
        - enable_ssl
        - ansible_os_family == "RedHat"

    - name: Obtain SSL certificate for domain
      ansible.builtin.command: >
        certbot --nginx
        -d {{ domain }}
        --non-interactive
        --agree-tos
        --email {{ admin_email }}
        --redirect
      when: enable_ssl
      register: certbot_result
      changed_when: "'Successfully received certificate' in certbot_result.stdout"

    - name: Apply optimized HTTPS configuration
      ansible.builtin.template:
        src: templates/nginx-https-postgresql-stack.conf.j2
        dest: "{{ '/etc/nginx/sites-available/postgresql-stack' if ansible_os_family == 'Debian' else '/etc/nginx/conf.d/postgresql-stack.conf' }}"
        mode: '0644'
      when: enable_ssl
      notify: Reload Nginx

    - name: Setup automatic certificate renewal
      ansible.builtin.cron:
        name: "Renew Let's Encrypt certificates"
        minute: "0"
        hour: "0,12"
        job: "certbot renew --quiet --post-hook 'systemctl reload nginx'"
      when: enable_ssl

    - name: Display installation summary
      ansible.builtin.debug:
        msg:
          - "PostgreSQL Stack installation complete!"
          - "============================================"
          - "Base URL: {{ 'https' if enable_ssl else 'http' }}://{{ domain }}"
          - ""
          - "Services:"
          - "  pgweb (Web UI):    {{ 'https' if enable_ssl else 'http' }}://{{ domain }}{{ pgweb_path }}/ (protected by Authelia 2FA)"
          - "  PostgREST API:     {{ 'https' if enable_ssl else 'http' }}://{{ domain }}{{ postgrest_path }}/ (requires JWT auth)"
          - "  Auth Service:      {{ 'https' if enable_ssl else 'http' }}://{{ domain }}{{ auth_path }}/ (JWT token generation)"
          - "  Authelia Portal:   {{ 'https' if enable_ssl else 'http' }}://{{ domain }}{{ authelia_path }}/ (2FA login page)"
          - ""
          - "PostgreSQL Credentials:"
          - "  User: {{ postgres_user }}"
          - "  Password: {{ postgres_password }}"
          - "  Database: {{ postgres_db }}"
          - ""
          - "JWT Auth API Credentials:"
          - "  API User:"
          - "    Username: api_user"
          - "    Password: {{ api_user_password }}"
          - "    Role: api_user (read/write access)"
          - "  API Admin:"
          - "    Username: admin"
          - "    Password: {{ api_admin_password }}"
          - "    Role: admin (full access)"
          - ""
          - "Authelia (protects pgweb only):"
          - "  Username: admin"
          - "  Password: {{ authelia_admin_password }}"
          - ""
          - "IMPORTANT: Save these credentials securely!"
          - ""
          - "Quick Start:"
          - "  1. Get JWT token: curl -X POST {{ 'https' if enable_ssl else 'http' }}://{{ domain }}{{ auth_path }}/login -H 'Content-Type: application/json' -d '{\"username\":\"api_user\",\"password\":\"{{ api_user_password }}\"}'"
          - "  2. Use token: curl {{ 'https' if enable_ssl else 'http' }}://{{ domain }}{{ postgrest_path }}/sample_data -H 'Authorization: Bearer YOUR_TOKEN'"
          - ""
          - "Installation directory: {{ install_dir }}"
          - "Data directory: {{ data_dir }}"
          - "Reverse Proxy: Nginx (path-based routing)"
          - "SSL Certificate: {{ 'Enabled (Let''s Encrypt)' if enable_ssl else 'Disabled' }}"
          - ""
          - "To manage the service:"
          - "  Start:   cd {{ install_dir }} && docker compose start"
          - "  Stop:    cd {{ install_dir }} && docker compose stop"
          - "  Restart: cd {{ install_dir }} && docker compose restart"
          - "  Logs:    cd {{ install_dir }} && docker compose logs -f"

  handlers:
    - name: Reload Nginx
      ansible.builtin.systemd:
        name: nginx
        state: reloaded
