---
- name: Uninstall PostgreSQL Stack (PostgreSQL 18 + PostgREST + pgweb + Authelia)
  hosts: all
  become: true
  vars:
    install_dir: "{{ install_dir | default('/opt/postgresql-stack') }}"
    data_dir: "{{ install_dir }}/data"
    pgweb_domain: "{{ pgweb_domain | default('') }}"
    postgrest_domain: "{{ postgrest_domain | default('') }}"

  tasks:
    - name: Check if installation directory exists
      ansible.builtin.stat:
        path: "{{ install_dir }}"
      register: install_dir_stat

    - name: Warn if installation not found
      ansible.builtin.debug:
        msg:
          - "WARNING: Installation directory not found at {{ install_dir }}"
          - "PostgreSQL Stack may not be installed or was installed in a different location."
      when: not install_dir_stat.stat.exists

    - name: Confirm data deletion
      ansible.builtin.pause:
        prompt: |

          ⚠️  WARNING: This will permanently delete all PostgreSQL data! ⚠️

          This includes:
          - All databases and tables
          - All Authelia user data and 2FA configurations
          - All configuration files

          Location: {{ install_dir }}

          Are you sure you want to continue? Type 'yes' to confirm
      register: confirm_delete
      when: install_dir_stat.stat.exists

    - name: Abort if not confirmed
      ansible.builtin.fail:
        msg: "Uninstallation aborted by user"
      when:
        - install_dir_stat.stat.exists
        - confirm_delete.user_input | default('') != 'yes'

    - name: Stop and remove Docker containers
      ansible.builtin.command: docker compose down -v
      args:
        chdir: "{{ install_dir }}"
      ignore_errors: true
      when: install_dir_stat.stat.exists

    - name: Remove PostgreSQL Stack Docker images
      ansible.builtin.shell: |
        docker rmi postgres:18.1-alpine || true
        docker rmi postgrest/postgrest:v12.2.3 || true
        docker rmi sosedoff/pgweb:0.16.2 || true
        docker rmi authelia/authelia:4.38.16 || true
      ignore_errors: true

    - name: Remove installation directory
      ansible.builtin.file:
        path: "{{ install_dir }}"
        state: absent
      when: install_dir_stat.stat.exists

    - name: Remove Nginx pgweb configuration (Debian/Ubuntu)
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/nginx/sites-enabled/postgresql-stack-pgweb
        - /etc/nginx/sites-available/postgresql-stack-pgweb
      when: ansible_os_family == "Debian"
      ignore_errors: true

    - name: Remove Nginx postgrest configuration (Debian/Ubuntu)
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/nginx/sites-enabled/postgresql-stack-postgrest
        - /etc/nginx/sites-available/postgresql-stack-postgrest
      when: ansible_os_family == "Debian"
      ignore_errors: true

    - name: Remove Nginx auth configuration (Debian/Ubuntu)
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/nginx/sites-enabled/postgresql-stack-auth
        - /etc/nginx/sites-available/postgresql-stack-auth
      when: ansible_os_family == "Debian"
      ignore_errors: true

    - name: Remove Nginx configuration (RHEL/CentOS/Rocky/Alma)
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/nginx/conf.d/postgresql-stack-pgweb.conf
        - /etc/nginx/conf.d/postgresql-stack-postgrest.conf
        - /etc/nginx/conf.d/postgresql-stack-auth.conf
      when: ansible_os_family == "RedHat"
      ignore_errors: true

    - name: Test Nginx configuration
      ansible.builtin.command: nginx -t
      register: nginx_test
      ignore_errors: true
      changed_when: false

    - name: Reload Nginx if configuration is valid
      ansible.builtin.systemd:
        name: nginx
        state: reloaded
      when: nginx_test.rc == 0
      ignore_errors: true

    - name: Remove SSL certificates for pgweb
      ansible.builtin.command: certbot delete --cert-name {{ pgweb_domain }} --non-interactive
      when:
        - pgweb_domain is defined
        - pgweb_domain | length > 0
      ignore_errors: true

    - name: Remove SSL certificates for postgrest
      ansible.builtin.command: certbot delete --cert-name {{ postgrest_domain }} --non-interactive
      when:
        - postgrest_domain is defined
        - postgrest_domain | length > 0
      ignore_errors: true

    - name: Remove SSL certificates for auth
      ansible.builtin.command: certbot delete --cert-name {{ auth_domain }} --non-interactive
      when:
        - auth_domain is defined
        - auth_domain | length > 0
      ignore_errors: true

    - name: Display uninstallation summary
      ansible.builtin.debug:
        msg:
          - "PostgreSQL Stack uninstallation complete!"
          - "============================================"
          - "Removed:"
          - "  - Docker containers and volumes"
          - "  - Installation directory: {{ install_dir }}"
          - "  - Nginx configurations"
          - "  - SSL certificates (if domains were provided)"
          - ""
          - "NOT removed (manual cleanup required if desired):"
          - "  - Docker"
          - "  - Nginx"
          - "  - Certbot"
          - ""
          - "To completely remove all components:"
          - "  Docker: apt remove docker-ce docker-ce-cli containerd.io (Debian/Ubuntu)"
          - "          yum remove docker-ce docker-ce-cli containerd.io (RHEL/CentOS)"
          - "  Nginx:  apt remove nginx (Debian/Ubuntu)"
          - "          yum remove nginx (RHEL/CentOS)"
          - "  Certbot: apt remove certbot python3-certbot-nginx (Debian/Ubuntu)"
          - "           yum remove certbot python3-certbot-nginx (RHEL/CentOS)"
