---
- name: Uninstall PostgreSQL Stack
  hosts: all
  become: true
  vars:
    install_dir: "/opt/pgstack"
    data_dir: "/opt/pgstack/data"
    project_name: "pgstack"

  tasks:
    - name: Check if installation directory exists
      ansible.builtin.stat:
        path: "{{ install_dir }}"
      register: install_dir_stat

    - name: Warn if installation not found
      ansible.builtin.debug:
        msg: "WARNING: Installation not found at {{ install_dir }}"
      when: not install_dir_stat.stat.exists

    - name: Display warning about data deletion
      ansible.builtin.debug:
        msg:
          - "WARNING: Permanently deleting all PostgreSQL data at {{ install_dir }}"
          - "This includes all databases, tables, and configuration files"
      when: install_dir_stat.stat.exists

    - name: Stop and remove Docker containers
      ansible.builtin.command: docker compose down -v
      args:
        chdir: "{{ install_dir }}"
      failed_when: false
      when: install_dir_stat.stat.exists

    - name: Force remove containers and network
      ansible.builtin.shell: |
        docker rm -f {{ project_name }}-db {{ project_name }}-postgrest {{ project_name }}-pgweb {{ project_name }}-auth {{ project_name }}-authelia 2>/dev/null || true
        docker network rm {{ project_name }}_default 2>/dev/null || true
      failed_when: false
      changed_when: false

    - name: Remove installation directory
      ansible.builtin.file:
        path: "{{ install_dir }}"
        state: absent
      when: install_dir_stat.stat.exists

    - name: Remove Nginx configuration (Debian/Ubuntu)
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/nginx/sites-enabled/{{ project_name }}
        - /etc/nginx/sites-available/{{ project_name }}
      when: ansible_os_family == "Debian"
      failed_when: false

    - name: Remove Nginx configuration (RHEL)
      ansible.builtin.file:
        path: /etc/nginx/conf.d/{{ project_name }}.conf
        state: absent
      when: ansible_os_family == "RedHat"
      failed_when: false

    - name: Test Nginx configuration
      ansible.builtin.command: nginx -t
      register: nginx_test
      failed_when: false
      changed_when: false

    - name: Reload Nginx if configuration is valid
      ansible.builtin.systemd:
        name: nginx
        state: reloaded
      when: nginx_test.rc == 0
      failed_when: false

    - name: Remove SSL certificate
      ansible.builtin.command: certbot delete --cert-name {{ domain }} --non-interactive
      changed_when: true
      when:
        - domain is defined
        - domain | length > 0
      failed_when: false

    - name: Display uninstallation summary
      ansible.builtin.debug:
        msg:
          - "PostgreSQL Stack uninstallation complete!"
          - "============================================"
          - "Removed:"
          - "  - Docker containers and volumes"
          - "  - Installation directory: {{ install_dir }}"
          - "  - Nginx configuration"
          - "  - SSL certificate (if domain was provided)"
