---
- name: Uninstall PostgreSQL Stack (PostgreSQL 18 + PostgREST + pgweb + Authelia)
  hosts: all
  become: true
  vars:
    install_dir: "{{ install_dir | default('/opt/postgresql-stack') }}"
    data_dir: "{{ install_dir }}/data"
    domain: "{{ domain | default('') }}"

  tasks:
    - name: Set project name based on install directory
      ansible.builtin.set_fact:
        project_name: "{{ install_dir | basename | regex_replace('[^a-zA-Z0-9]', '') }}"
    - name: Check if installation directory exists
      ansible.builtin.stat:
        path: "{{ install_dir }}"
      register: install_dir_stat

    - name: Warn if installation not found
      ansible.builtin.debug:
        msg:
          - "WARNING: Installation directory not found at {{ install_dir }}"
          - "PostgreSQL Stack may not be installed or was installed in a different location."
      when: not install_dir_stat.stat.exists

    - name: Display warning about data deletion
      ansible.builtin.debug:
        msg:
          - "⚠️  WARNING: Permanently deleting all PostgreSQL data at {{ install_dir }}"
          - "This includes all databases, tables, Authelia user data, and configuration files"
      when: install_dir_stat.stat.exists

    - name: Stop and remove Docker containers
      ansible.builtin.command: docker compose down -v
      args:
        chdir: "{{ install_dir }}"
      failed_when: false
      when: install_dir_stat.stat.exists

    - name: Force remove containers and network (in case of conflicts)
      ansible.builtin.shell: |
        docker rm -f {{ project_name }}-db {{ project_name }}-postgrest {{ project_name }}-pgweb {{ project_name }}-auth {{ project_name }}-authelia 2>/dev/null || true
        docker network rm {{ project_name }}_default 2>/dev/null || true
      failed_when: false
      changed_when: false

    - name: Remove PostgreSQL Stack Docker images
      ansible.builtin.shell: |
        set -o pipefail
        docker rmi postgres:18.1-alpine || true
        docker rmi postgrest/postgrest:v12.2.3 || true
        docker rmi sosedoff/pgweb:0.16.2 || true
        docker rmi authelia/authelia:4.38.16 || true
      failed_when: false

    - name: Remove installation directory
      ansible.builtin.file:
        path: "{{ install_dir }}"
        state: absent
      when: install_dir_stat.stat.exists

    - name: Remove Nginx configuration (Debian/Ubuntu)
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/nginx/sites-enabled/{{ project_name }}
        - /etc/nginx/sites-available/{{ project_name }}
      when: ansible_os_family == "Debian"
      failed_when: false

    - name: Remove Nginx configuration (RHEL/CentOS/Rocky/Alma)
      ansible.builtin.file:
        path: /etc/nginx/conf.d/{{ project_name }}.conf
        state: absent
      when: ansible_os_family == "RedHat"
      failed_when: false

    - name: Test Nginx configuration
      ansible.builtin.command: nginx -t
      register: nginx_test
      failed_when: false
      changed_when: false

    - name: Reload Nginx if configuration is valid
      ansible.builtin.systemd:
        name: nginx
        state: reloaded
      when: nginx_test.rc == 0
      failed_when: false

    - name: Remove SSL certificate
      ansible.builtin.command: certbot delete --cert-name {{ domain }} --non-interactive
      changed_when: true
      when:
        - domain is defined
        - domain | length > 0
      failed_when: false

    - name: Display uninstallation summary
      ansible.builtin.debug:
        msg:
          - "PostgreSQL Stack uninstallation complete!"
          - "============================================"
          - "Removed:"
          - "  - Docker containers and volumes"
          - "  - Installation directory: {{ install_dir }}"
          - "  - Nginx configuration"
          - "  - SSL certificate (if domain was provided)"
          - ""
          - "NOT removed (manual cleanup required if desired):"
          - "  - Docker"
          - "  - Nginx"
          - "  - Certbot"
          - ""
          - "To completely remove all components:"
          - "  Docker: apt remove docker-ce docker-ce-cli containerd.io (Debian/Ubuntu)"
          - "          dnf remove docker-ce docker-ce-cli containerd.io (RHEL 8+/Rocky/Alma)"
          - "  Nginx:  apt remove nginx (Debian/Ubuntu)"
          - "          dnf remove nginx (RHEL 8+/Rocky/Alma)"
          - "  Certbot: apt remove certbot python3-certbot-nginx (Debian/Ubuntu)"
          - "           dnf remove certbot python3-certbot-nginx (RHEL 8+/Rocky/Alma)"
