---
- name: Update PostgreSQL Stack Configuration
  hosts: all
  become: true
  vars:
    # Hardcoded paths
    install_dir: "/opt/pgstack"
    data_dir: "/opt/pgstack/data"
    project_name: "pgstack"

    # Hardcoded service paths
    pgweb_path: "/pgweb"
    postgrest_path: "/postgrest"
    auth_path: "/auth"
    authelia_path: "/authelia"

    # Hardcoded ports
    postgres_port: 5432
    postgrest_port: 3000
    pgweb_port: 8081
    authelia_port: 9091
    auth_port: 5000

    # Hardcoded database settings
    postgres_db: "postgres"
    postgres_user: "postgres"
    postgrest_role: "authenticator"
    postgrest_anon_role: "anon"

    # SSL always enabled
    enable_ssl: true

  tasks:
    - name: Validate required variables
      ansible.builtin.assert:
        that:
          - domain is defined
          - domain | length > 0
        fail_msg: "Missing required variable: domain"

    - name: Check if installation exists
      ansible.builtin.stat:
        path: "{{ install_dir }}/compose.yml"
      register: install_check

    - name: Fail if installation not found
      ansible.builtin.fail:
        msg: |
          ERROR: PostgreSQL Stack installation not found at {{ install_dir }}
          Run install.yml first: ansible-playbook install.yml -e domain={{ domain }} -e admin_email=you@example.com
      when: not install_check.stat.exists

    - name: Display update information
      ansible.builtin.debug:
        msg:
          - "Updating PostgreSQL Stack at {{ install_dir }}"
          - "Domain: {{ domain }}"

    # Load existing credentials from .env
    - name: Load existing credentials from .env
      ansible.builtin.shell: |
        set -o pipefail
        grep '^{{ item }}=' {{ install_dir }}/.env | cut -d= -f2
      register: existing_credentials
      loop:
        - POSTGRES_PASSWORD
        - POSTGREST_PASSWORD
        - POSTGREST_JWT_SECRET
        - AUTHELIA_JWT_SECRET
        - AUTHELIA_SESSION_SECRET
        - AUTHELIA_STORAGE_ENCRYPTION_KEY
        - AUTHELIA_ADMIN_PASSWORD
        - API_USER_PASSWORD
        - API_ADMIN_PASSWORD
      changed_when: false
      failed_when: false

    - name: Set credentials from existing .env
      ansible.builtin.set_fact:
        postgres_password: "{{ existing_credentials.results[0].stdout }}"
        postgrest_password: "{{ existing_credentials.results[1].stdout }}"
        postgrest_jwt_secret: "{{ existing_credentials.results[2].stdout }}"
        authelia_jwt_secret: "{{ existing_credentials.results[3].stdout }}"
        authelia_session_secret: "{{ existing_credentials.results[4].stdout }}"
        authelia_storage_encryption_key: "{{ existing_credentials.results[5].stdout }}"
        authelia_admin_password: "{{ existing_credentials.results[6].stdout }}"
        api_user_password: "{{ existing_credentials.results[7].stdout }}"
        api_admin_password: "{{ existing_credentials.results[8].stdout }}"

    # Load existing Authelia password hash
    - name: Load existing Authelia password hash
      ansible.builtin.shell: |
        set -o pipefail
        grep -oE '\$argon2id\$v=[0-9]+\$m=[0-9]+,t=[0-9]+,p=[0-9]+\$[A-Za-z0-9+/]+\$[A-Za-z0-9+/]+' {{ install_dir }}/authelia-users.yml | head -1
      register: existing_authelia_hash
      changed_when: false
      failed_when: false

    - name: Set Authelia admin password hash
      ansible.builtin.set_fact:
        authelia_admin_password_hash: "{{ existing_authelia_hash.stdout }}"

    # Update configuration files
    - name: Update .env file
      ansible.builtin.template:
        src: templates/env.j2
        dest: "{{ install_dir }}/.env"
        mode: '0600'
      register: env_updated

    - name: Update compose.yml
      ansible.builtin.template:
        src: templates/compose.yml.j2
        dest: "{{ install_dir }}/compose.yml"
        mode: '0644'
      register: compose_updated

    - name: Update PostgREST configuration
      ansible.builtin.template:
        src: templates/postgrest.conf.j2
        dest: "{{ install_dir }}/postgrest.conf"
        mode: '0644'
      register: postgrest_conf_updated

    - name: Update Authelia configuration
      ansible.builtin.template:
        src: templates/authelia-config.yml.j2
        dest: "{{ install_dir }}/authelia-config.yml"
        mode: '0600'
      register: authelia_config_updated

    - name: Update Authelia users database
      ansible.builtin.template:
        src: templates/authelia-users.yml.j2
        dest: "{{ install_dir }}/authelia-users.yml"
        mode: '0600'
      register: authelia_users_updated

    - name: Update PostgreSQL init script
      ansible.builtin.template:
        src: templates/init-postgrest.sql.j2
        dest: "{{ install_dir }}/init-postgrest.sql"
        mode: '0644'

    - name: Update Auth service Python script
      ansible.builtin.template:
        src: templates/auth-service.py.j2
        dest: "{{ install_dir }}/auth-service.py"
        mode: '0755'
      register: auth_service_updated

    - name: Update Auth service requirements file
      ansible.builtin.template:
        src: templates/auth-requirements.txt.j2
        dest: "{{ install_dir }}/auth-requirements.txt"
        mode: '0644'

    - name: Update Auth service Dockerfile
      ansible.builtin.template:
        src: templates/Dockerfile.auth.j2
        dest: "{{ install_dir }}/Dockerfile.auth"
        mode: '0644'
      register: auth_dockerfile_updated

    # Update Nginx configuration
    - name: Update Nginx HTTPS configuration (Debian/Ubuntu)
      ansible.builtin.template:
        src: templates/nginx-https-postgresql-stack.conf.j2
        dest: "/etc/nginx/sites-available/{{ project_name }}"
        mode: '0644'
        force: true
      when: ansible_os_family == "Debian"
      register: nginx_updated_debian

    - name: Update Nginx HTTPS configuration (RHEL)
      ansible.builtin.template:
        src: templates/nginx-https-postgresql-stack.conf.j2
        dest: "/etc/nginx/conf.d/{{ project_name }}.conf"
        mode: '0644'
        force: true
      when: ansible_os_family == "RedHat"
      register: nginx_updated_rhel

    - name: Test Nginx configuration
      ansible.builtin.command: nginx -t
      changed_when: false

    - name: Reload Nginx
      ansible.builtin.systemd:
        name: nginx
        state: reloaded
      when: nginx_updated_debian.changed or nginx_updated_rhel.changed

    # Restart services if needed
    - name: Restart Docker containers if configuration changed
      ansible.builtin.command: docker compose up -d
      args:
        chdir: "{{ install_dir }}"
      when: >
        env_updated.changed or
        compose_updated.changed or
        postgrest_conf_updated.changed or
        authelia_config_updated.changed or
        authelia_users_updated.changed or
        auth_service_updated.changed or
        auth_dockerfile_updated.changed
      register: docker_restart
      changed_when: "'Started' in docker_restart.stderr or 'Recreated' in docker_restart.stderr"

    - name: Display update summary
      ansible.builtin.debug:
        msg:
          - "PostgreSQL Stack update complete!"
          - "============================================"
          - "Base URL: https://{{ domain }}"
          - ""
          - "Services:"
          - "  pgweb:     https://{{ domain }}/pgweb/"
          - "  PostgREST: https://{{ domain }}/postgrest/"
          - "  Auth:      https://{{ domain }}/auth/"
          - "  Authelia:  https://{{ domain }}/authelia/"
