---
- name: Install and Configure Fail2Ban
  hosts: all
  become: true

  vars:
    supported_os_families:
      - Debian
      - RedHat
    ssh_log_paths:
      Debian: /var/log/auth.log
      RedHat: /var/log/secure
    ssh_log_path: "{{ ssh_log_paths.get(ansible_os_family, '/var/log/auth.log') }}"
    # Default values (can be overridden)
    bantime: 3600           # 1 hour
    findtime: 600           # 10 minutes
    maxretry: 5             # 5 failed attempts
    ssh_port: 22            # Default SSH port
    webhook_url: ""         # Optional webhook URL for notifications

  pre_tasks:
    - name: Verify supported operating system
      assert:
        that:
          - ansible_os_family in supported_os_families
        fail_msg: "This playbook currently supports Debian/Ubuntu and RedHat-family distributions (RHEL/Rocky/Fedora/Amazon Linux)."

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_pkg_mgr == "apt"

    - name: Install fail2ban package
      apt:
        name: fail2ban
        state: present
      when: ansible_pkg_mgr == "apt"

    - name: Install fail2ban package (RPM-based)
      package:
        name: fail2ban
        state: present
      when: ansible_pkg_mgr in ["dnf", "yum", "microdnf"]

    - name: Ensure fail2ban configuration directory exists
      file:
        path: /etc/fail2ban
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Ensure fail2ban jail.d directory exists
      file:
        path: /etc/fail2ban/jail.d
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Ensure fail2ban action.d directory exists
      file:
        path: /etc/fail2ban/action.d
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Deploy jail.local configuration
      template:
        src: templates/jail.local.j2
        dest: /etc/fail2ban/jail.local
        owner: root
        group: root
        mode: '0644'
      notify: Restart fail2ban

    - name: Deploy SSH jail configuration
      template:
        src: templates/sshd.local.j2
        dest: /etc/fail2ban/jail.d/sshd.local
        owner: root
        group: root
        mode: '0644'
      notify: Restart fail2ban

    - name: Deploy webhook action configuration
      template:
        src: templates/webhook.conf.j2
        dest: /etc/fail2ban/action.d/webhook.conf
        owner: root
        group: root
        mode: '0644'
      when: webhook_url != ""
      notify: Restart fail2ban

    - name: Ensure fail2ban service is enabled and started
      systemd:
        name: fail2ban
        enabled: yes
        state: started

    - name: Check fail2ban status
      command: fail2ban-client status
      register: fail2ban_status
      changed_when: false

    - name: Display fail2ban status
      debug:
        var: fail2ban_status.stdout_lines

  handlers:
    - name: Restart fail2ban
      systemd:
        name: fail2ban
        state: restarted
