---
- name: Install Umami Web Analytics with Nginx
  hosts: all
  become: yes
  vars:
    umami_install_dir: "{{ umami_install_dir | default('/opt/umami') }}"
    umami_data_dir: "{{ umami_install_dir }}/data"
    umami_port: "{{ umami_port | default(3000) }}"
    postgres_user: "{{ postgres_user | default('umami') }}"
    postgres_db: "{{ postgres_db | default('umami') }}"
    umami_version: "{{ umami_version | default('postgresql-latest') }}"
    enable_ssl: "{{ enable_ssl | default(true) }}"

  tasks:
    - name: Validate required variables
      assert:
        that:
          - umami_domain is defined
          - umami_domain | length > 0
          - enable_ssl == false or (admin_email is defined and admin_email | length > 0)
        fail_msg: "Missing required variables. umami_domain is required. admin_email is required when enable_ssl is true."

    - name: Generate PostgreSQL password if not provided
      set_fact:
        postgres_password: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}"
      when: postgres_password is not defined or postgres_password | length == 0

    - name: Generate application secret if not provided
      set_fact:
        app_secret: "{{ lookup('password', '/dev/null length=64 chars=ascii_letters,digits') }}"
      when: app_secret is not defined or app_secret | length == 0

    # Nginx Detection Logic
    - name: Check if system Nginx is installed
      command: which nginx
      register: nginx_binary
      ignore_errors: yes
      changed_when: false

    - name: Check if ports 80 and 443 are in use
      shell: |
        port80=$(ss -tuln | grep ':80 ' || echo "free")
        port443=$(ss -tuln | grep ':443 ' || echo "free")
        if [[ "$port80" != "free" ]] || [[ "$port443" != "free" ]]; then
          echo "in_use"
        else
          echo "free"
        fi
      register: ports_check
      changed_when: false

    - name: Fail if ports are occupied and Nginx is not installed
      fail:
        msg: |
          ERROR: Ports 80 and/or 443 are already in use, but Nginx is not installed.

          This playbook uses system Nginx for multi-app support.
          Options:
          1. Free up ports 80/443 and re-run (playbook will install system Nginx)
          2. Install Nginx manually first

          If you prefer Caddy, use the umami-v3-postgresql-caddy playbook variant.
      when:
        - nginx_binary.rc != 0
        - ports_check.stdout == 'in_use'

    - name: Display Nginx deployment decision
      debug:
        msg:
          - "Deploying with system Nginx + Certbot SSL (supports multiple applications on one server)"
          - "{{ 'Will use existing Nginx installation' if nginx_binary.rc == 0 else 'Will install Nginx from distribution repository' }}"
          - "SSL: Automatic via Certbot"

    - name: Install required packages
      package:
        name:
          - curl
          - ca-certificates
          - gnupg
        state: present

    - name: Check if Docker is installed
      command: docker --version
      register: docker_installed
      ignore_errors: yes
      changed_when: false

    - name: Install Docker (Debian/Ubuntu)
      block:
        - name: Add Docker GPG key
          apt_key:
            url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
            state: present

        - name: Add Docker repository
          apt_repository:
            repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
            state: present

        - name: Install Docker packages
          apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-compose-plugin
            state: present
            update_cache: yes
      when:
        - docker_installed.rc != 0
        - ansible_os_family == "Debian"

    - name: Install Docker (RHEL/CentOS/Rocky/Alma)
      block:
        - name: Add Docker repository
          yum_repository:
            name: docker-ce
            description: Docker CE Stable
            baseurl: "https://download.docker.com/linux/{{ 'centos' if ansible_distribution == 'CentOS' else 'rhel' if ansible_distribution in ['RedHat', 'OracleLinux'] else ansible_distribution | lower }}/{{ ansible_distribution_major_version }}/$basearch/stable"
            gpgcheck: yes
            gpgkey: "https://download.docker.com/linux/{{ 'centos' if ansible_distribution == 'CentOS' else 'rhel' if ansible_distribution in ['RedHat', 'OracleLinux'] else ansible_distribution | lower }}/gpg"
            enabled: yes

        - name: Install Docker packages
          yum:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-compose-plugin
            state: present
      when:
        - docker_installed.rc != 0
        - ansible_os_family == "RedHat"

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Create Umami directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ umami_install_dir }}"
        - "{{ umami_data_dir }}"

    - name: Create .env file
      template:
        src: templates/env.j2
        dest: "{{ umami_install_dir }}/.env"
        mode: '0600'

    - name: Create compose.yml
      template:
        src: templates/compose.yml.j2
        dest: "{{ umami_install_dir }}/compose.yml"
        mode: '0644'

    # System Nginx Mode - Install or use existing Nginx installation
    - name: Check if system Nginx is already installed
      command: which nginx
      register: system_nginx_check
      ignore_errors: yes
      changed_when: false

    - name: Install Nginx (Debian/Ubuntu)
      apt:
        name: nginx
        state: present
        update_cache: yes
      when:
        - system_nginx_check.rc != 0
        - ansible_os_family == "Debian"

    - name: Install Nginx (RHEL/CentOS/Rocky/Alma)
      yum:
        name: nginx
        state: present
      when:
        - system_nginx_check.rc != 0
        - ansible_os_family == "RedHat"

    - name: Start and enable Nginx service
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Create initial HTTP Nginx configuration (for Certbot validation)
      template:
        src: templates/nginx-http.conf.j2
        dest: /etc/nginx/sites-available/umami
        mode: '0644'
      when: ansible_os_family == "Debian"

    - name: Create initial HTTP Nginx configuration (for Certbot validation) - RHEL
      template:
        src: templates/nginx-http.conf.j2
        dest: /etc/nginx/conf.d/umami.conf
        mode: '0644'
      when: ansible_os_family == "RedHat"

    - name: Enable Nginx site (Debian/Ubuntu)
      file:
        src: /etc/nginx/sites-available/umami
        dest: /etc/nginx/sites-enabled/umami
        state: link
      when: ansible_os_family == "Debian"
      notify: reload_nginx

    - name: Test Nginx configuration
      command: nginx -t
      changed_when: false

    - name: Reload Nginx
      systemd:
        name: nginx
        state: reloaded

    - name: Pull Umami Docker images
      command: docker compose pull
      args:
        chdir: "{{ umami_install_dir }}"
      register: docker_pull
      changed_when: "'Downloaded' in docker_pull.stderr or 'Pulled' in docker_pull.stderr"

    - name: Start Umami services
      command: docker compose up -d
      args:
        chdir: "{{ umami_install_dir }}"
      register: docker_up
      changed_when: "'Started' in docker_up.stderr or 'Created' in docker_up.stderr"

    - name: Wait for Umami to be ready
      uri:
        url: "http://localhost:{{ umami_port }}/api/heartbeat"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 30
      delay: 10

    # SSL Certificate with Certbot
    - name: Install Certbot (Debian/Ubuntu)
      apt:
        name:
          - certbot
          - python3-certbot-nginx
        state: present
      when:
        - enable_ssl
        - ansible_os_family == "Debian"

    - name: Install Certbot (RHEL/Rocky/Alma)
      yum:
        name:
          - certbot
          - python3-certbot-nginx
        state: present
      when:
        - enable_ssl
        - ansible_os_family == "RedHat"

    - name: Obtain SSL certificate with Certbot
      command: >
        certbot --nginx
        -d {{ umami_domain }}
        --non-interactive
        --agree-tos
        --email {{ admin_email }}
        --redirect
      when: enable_ssl
      register: certbot_result
      changed_when: "'Successfully received certificate' in certbot_result.stdout"

    - name: Update Nginx configuration with SSL optimizations
      template:
        src: templates/nginx-https.conf.j2
        dest: "{{ '/etc/nginx/sites-available/umami' if ansible_os_family == 'Debian' else '/etc/nginx/conf.d/umami.conf' }}"
        mode: '0644'
      when: enable_ssl
      notify: reload_nginx

    - name: Setup automatic certificate renewal
      cron:
        name: "Renew Let's Encrypt certificates"
        minute: "0"
        hour: "0,12"
        job: "certbot renew --quiet --post-hook 'systemctl reload nginx'"
      when: enable_ssl

    - name: Display installation summary
      debug:
        msg:
          - "Umami Web Analytics installation complete!"
          - "============================================"
          - "Access URL: {{ 'https' if enable_ssl else 'http' }}://{{ umami_domain }}"
          - "Default credentials:"
          - "  Username: admin"
          - "  Password: umami"
          - ""
          - "IMPORTANT: Please change the default password immediately after first login!"
          - ""
          - "Installation directory: {{ umami_install_dir }}"
          - "Data directory: {{ umami_data_dir }}"
          - "Database: PostgreSQL ({{ postgres_db }})"
          - "Reverse Proxy: Nginx"
          - "SSL Certificate: {{ 'Enabled (Let''s Encrypt)' if enable_ssl else 'Disabled' }}"
          - ""
          - "To manage the service:"
          - "  Start:   cd {{ umami_install_dir }} && docker compose start"
          - "  Stop:    cd {{ umami_install_dir }} && docker compose stop"
          - "  Restart: cd {{ umami_install_dir }} && docker compose restart"
          - "  Logs:    cd {{ umami_install_dir }} && docker compose logs -f"

  handlers:
    - name: reload_nginx
      systemd:
        name: nginx
        state: reloaded
