---
- name: Uninstall Umami Web Analytics
  hosts: all
  become: true
  vars:
    umami_install_dir: "{{ umami_install_dir | default('/opt/umami') }}"
    umami_data_dir: "{{ umami_install_dir }}/data"

  tasks:
    - name: Check if Umami installation exists
      ansible.builtin.stat:
        path: "{{ umami_install_dir }}/compose.yml"
      register: umami_exists

    - name: Stop and remove Umami containers
      ansible.builtin.command: docker compose down -v
      args:
        chdir: "{{ umami_install_dir }}"
      when: umami_exists.stat.exists
      ignore_errors: true

    - name: Remove Umami Docker images
      ansible.builtin.command: docker compose down --rmi all
      args:
        chdir: "{{ umami_install_dir }}"
      when: umami_exists.stat.exists
      ignore_errors: true

    - name: Prompt for data deletion
      ansible.builtin.pause:
        prompt: |

          WARNING: Do you want to delete all Umami data including analytics database?
          This action is irreversible and will delete:
            - All analytics data in {{ umami_data_dir }}
            - PostgreSQL database and volumes
            - Configuration files

          Type 'yes' to confirm data deletion, or 'no' to keep data
      register: delete_data_prompt
      when: umami_exists.stat.exists

    - name: Remove Umami data directory
      ansible.builtin.file:
        path: "{{ umami_data_dir }}"
        state: absent
      when:
        - umami_exists.stat.exists
        - delete_data_prompt.user_input | default('no') | lower == 'yes'

    - name: Remove Umami installation directory
      ansible.builtin.file:
        path: "{{ umami_install_dir }}"
        state: absent
      when: umami_exists.stat.exists

    - name: Remove Nginx configuration (Debian/Ubuntu)
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/nginx/sites-enabled/umami
        - /etc/nginx/sites-available/umami
      when: ansible_os_family == "Debian"
      ignore_errors: true

    - name: Remove Nginx configuration (RHEL/CentOS/Rocky/Alma)
      ansible.builtin.file:
        path: /etc/nginx/conf.d/umami.conf
        state: absent
      when: ansible_os_family == "RedHat"
      ignore_errors: true

    - name: Test Nginx configuration
      ansible.builtin.command: nginx -t
      register: nginx_test
      ignore_errors: true
      changed_when: false

    - name: Reload Nginx if configuration is valid
      ansible.builtin.systemd:
        name: nginx
        state: reloaded
      when: nginx_test.rc == 0
      ignore_errors: true

    - name: Remove SSL certificates
      ansible.builtin.command: certbot delete --cert-name {{ umami_domain }} --non-interactive
      when:
        - umami_domain is defined
        - umami_domain | length > 0
      ignore_errors: true

    - name: Remove Certbot cron job
      ansible.builtin.cron:
        name: "Renew Let's Encrypt certificates"
        state: absent
      ignore_errors: true

    - name: Display uninstall summary
      ansible.builtin.debug:
        msg:
          - "Umami Web Analytics has been uninstalled!"
          - "=========================================="
          - "Removed:"
          - "  - Docker containers and images"
          - "  - Configuration files"
          - "  - Nginx configurations"
          - "  - SSL certificates (if domain was provided)"
          - "  - Certbot renewal cron job"
          - "{{ '  - Analytics data and database' if (delete_data_prompt.user_input | default('no') | lower == 'yes') else '  - Analytics data preserved in ' + umami_data_dir }}"
          - ""
          - "NOT removed (manual cleanup required if desired):"
          - "  - Docker"
          - "  - Nginx"
          - "  - Certbot"
          - ""
          - "To completely remove all components:"
          - "  Docker: apt remove docker-ce docker-ce-cli containerd.io (Debian/Ubuntu)"
          - "          yum remove docker-ce docker-ce-cli containerd.io (RHEL/CentOS)"
          - "  Nginx:  apt remove nginx (Debian/Ubuntu)"
          - "          yum remove nginx (RHEL/CentOS)"
          - "  Certbot: apt remove certbot python3-certbot-nginx (Debian/Ubuntu)"
          - "           yum remove certbot python3-certbot-nginx (RHEL/CentOS)"
      when: umami_exists.stat.exists

    - name: Display message if Umami not found
      ansible.builtin.debug:
        msg: "Umami installation not found at {{ umami_install_dir }}"
      when: not umami_exists.stat.exists
