---
- name: Install Umami Web Analytics
  hosts: all
  become: true
  vars:
    umami_install_dir: "{{ umami_install_dir | default('/opt/umami') }}"
    umami_data_dir: "{{ umami_install_dir }}/data"
    umami_port: "{{ umami_port | default(3000) }}"
    postgres_user: "{{ postgres_user | default('umami') }}"
    postgres_db: "{{ postgres_db | default('umami') }}"
    umami_version: "postgresql-latest"
    enable_ssl: "{{ enable_ssl | default(true) }}"

  tasks:
    - name: Validate required variables
      ansible.builtin.assert:
        that:
          - umami_domain is defined
          - umami_domain | length > 0
          - enable_ssl == false or (admin_email is defined and admin_email | length > 0)
        fail_msg: "Missing required variables. umami_domain is required. admin_email is required when enable_ssl is true."

    - name: Generate PostgreSQL password if not provided
      ansible.builtin.set_fact:
        postgres_password: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}"
      when: postgres_password is not defined or postgres_password | length == 0

    - name: Generate application secret if not provided
      ansible.builtin.set_fact:
        app_secret: "{{ lookup('password', '/dev/null length=64 chars=ascii_letters,digits') }}"
      when: app_secret is not defined or app_secret | length == 0

    # Caddy Detection Logic
    - name: Check if system Caddy is installed
      ansible.builtin.command: which caddy
      register: caddy_binary
      failed_when: false
      changed_when: false

    - name: Check if ports 80 and 443 are in use
      ansible.builtin.shell: |
        set -o pipefail
        port80=$(ss -tuln | grep ':80 ' || echo "free")
        port443=$(ss -tuln | grep ':443 ' || echo "free")
        if [[ "$port80" != "free" ]] || [[ "$port443" != "free" ]]; then
          echo "in_use"
        else
          echo "free"
        fi
      register: ports_check
      changed_when: false

    - name: Fail if ports are occupied and Caddy is not installed
      ansible.builtin.fail:
        msg: |
          ERROR: Ports 80 and/or 443 are already in use, but Caddy is not installed.

          This playbook uses system Caddy for multi-app support.
          Options:
          1. Free up ports 80/443 and re-run (playbook will install system Caddy)
          2. Install Caddy manually first

          If you prefer Nginx, use the umami-v3-postgresql-nginx playbook variant.
      when:
        - caddy_binary.rc != 0
        - ports_check.stdout == 'in_use'

    - name: Display Caddy deployment decision
      ansible.builtin.debug:
        msg:
          - "Deploying with system Caddy (supports multiple applications on one server)"
          - "{{ 'Will use existing Caddy installation' if caddy_binary.rc == 0 else 'Will install Caddy from official repository' }}"
          - "Configuration: /etc/caddy/conf.d/umami.conf"

    - name: Install required packages
      ansible.builtin.package:
        name:
          - curl
          - ca-certificates
          - gnupg
        state: present

    - name: Check if Docker is installed
      ansible.builtin.command: docker --version
      register: docker_installed
      failed_when: false
      changed_when: false

    - name: Install Docker (Debian/Ubuntu)
      block:
        - name: Add Docker GPG key
          ansible.builtin.apt_key:
            url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
            state: present

        - name: Add Docker repository
          ansible.builtin.apt_repository:
            repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
            state: present

        - name: Install Docker packages
          ansible.builtin.apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-compose-plugin
            state: present
            update_cache: true
      when:
        - docker_installed.rc != 0
        - ansible_os_family == "Debian"

    - name: Install Docker (RHEL/CentOS/Rocky/Alma)
      block:
        - name: Add Docker repository
          ansible.builtin.yum_repository:
            name: docker-ce
            description: Docker CE Stable
            baseurl: "https://download.docker.com/linux/{{ 'centos' if ansible_distribution == 'CentOS' else 'rhel' if ansible_distribution in ['RedHat', 'OracleLinux'] else ansible_distribution | lower }}/{{ ansible_distribution_major_version }}/$basearch/stable"
            gpgcheck: true
            gpgkey: "https://download.docker.com/linux/{{ 'centos' if ansible_distribution == 'CentOS' else 'rhel' if ansible_distribution in ['RedHat', 'OracleLinux'] else ansible_distribution | lower }}/gpg"
            enabled: true

        - name: Install Docker packages
          ansible.builtin.yum:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-compose-plugin
            state: present
      when:
        - docker_installed.rc != 0
        - ansible_os_family == "RedHat"

    - name: Start and enable Docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true

    - name: Create Umami directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ umami_install_dir }}"
        - "{{ umami_data_dir }}"

    - name: Create .env file
      ansible.builtin.template:
        src: templates/env.j2
        dest: "{{ umami_install_dir }}/.env"
        mode: '0600'

    - name: Create compose.yml
      ansible.builtin.template:
        src: templates/compose.yml.j2
        dest: "{{ umami_install_dir }}/compose.yml"
        mode: '0644'

    # System Caddy - Install or use existing Caddy installation
    - name: Check if system Caddy is already installed
      ansible.builtin.command: which caddy
      register: system_caddy_check
      failed_when: false
      changed_when: false

    - name: Install Caddy from official repository (Debian/Ubuntu)
      block:
        - name: Install Caddy dependencies
          ansible.builtin.apt:
            name:
              - debian-keyring
              - debian-archive-keyring
              - apt-transport-https
            state: present
            update_cache: true

        - name: Add Caddy GPG key
          ansible.builtin.apt_key:
            url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
            state: present

        - name: Add Caddy repository
          ansible.builtin.apt_repository:
            repo: "deb https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main"
            state: present
            filename: caddy-stable

        - name: Install Caddy
          ansible.builtin.apt:
            name: caddy
            state: present
            update_cache: true
      when:
        - system_caddy_check.rc != 0
        - ansible_os_family == "Debian"

    - name: Install Caddy from official repository (RHEL/CentOS/Rocky/Alma)
      block:
        - name: Add Caddy repository
          ansible.builtin.yum_repository:
            name: caddy
            description: Caddy Repository
            baseurl: https://dl.cloudsmith.io/public/caddy/stable/rpm/el/$releasever/$basearch
            gpgcheck: true
            gpgkey: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
            enabled: true

        - name: Install Caddy
          ansible.builtin.yum:
            name: caddy
            state: present
      when:
        - system_caddy_check.rc != 0
        - ansible_os_family == "RedHat"

    - name: Start and enable Caddy service
      ansible.builtin.systemd:
        name: caddy
        state: started
        enabled: true

    - name: Ensure /etc/caddy/conf.d directory exists
      ansible.builtin.file:
        path: /etc/caddy/conf.d
        state: directory
        mode: '0755'

    - name: Create Umami configuration for system Caddy
      ansible.builtin.template:
        src: templates/umami-system.conf.j2
        dest: /etc/caddy/conf.d/umami.conf
        mode: '0644'
      notify: Reload Caddy

    - name: Check if import directive exists in main Caddyfile
      ansible.builtin.shell: grep -q "import /etc/caddy/conf.d/\*.conf" /etc/caddy/Caddyfile || echo "missing"
      register: import_check
      changed_when: false

    - name: Add import directive to main Caddyfile if missing
      ansible.builtin.lineinfile:
        path: /etc/caddy/Caddyfile
        line: "import /etc/caddy/conf.d/*.conf"
        insertafter: EOF
        create: false
      when: import_check.stdout == 'missing'
      notify: Reload Caddy

    - name: Pull Umami Docker images
      ansible.builtin.command: docker compose pull
      args:
        chdir: "{{ umami_install_dir }}"
      register: docker_pull
      changed_when: "'Downloaded' in docker_pull.stderr or 'Pulled' in docker_pull.stderr"

    - name: Start Umami services
      ansible.builtin.command: docker compose up -d
      args:
        chdir: "{{ umami_install_dir }}"
      register: docker_up
      changed_when: "'Started' in docker_up.stderr or 'Created' in docker_up.stderr"

    - name: Wait for Umami to be ready
      ansible.builtin.uri:
        url: "http://localhost:{{ umami_port }}/api/heartbeat"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 30
      delay: 10

    - name: Display installation summary
      ansible.builtin.debug:
        msg:
          - "Umami Web Analytics installation complete!"
          - "============================================"
          - "Access URL: {{ 'https' if enable_ssl else 'http' }}://{{ umami_domain }}"
          - "Default credentials:"
          - "  Username: admin"
          - "  Password: umami"
          - ""
          - "IMPORTANT: Please change the default password immediately after first login!"
          - ""
          - "Installation directory: {{ umami_install_dir }}"
          - "Data directory: {{ umami_data_dir }}"
          - "Database: PostgreSQL ({{ postgres_db }})"
          - ""
          - "To manage the service:"
          - "  Start:   cd {{ umami_install_dir }} && docker compose start"
          - "  Stop:    cd {{ umami_install_dir }} && docker compose stop"
          - "  Restart: cd {{ umami_install_dir }} && docker compose restart"
          - "  Logs:    cd {{ umami_install_dir }} && docker compose logs -f"

  handlers:
    - name: Reload Caddy
      ansible.builtin.systemd:
        name: caddy
        state: reloaded
