---
- name: Uninstall Umami Web Analytics
  hosts: all
  become: true
  vars:
    umami_install_dir: "{{ umami_install_dir | default('/opt/umami') }}"
    umami_data_dir: "{{ umami_install_dir }}/data"

  tasks:
    - name: Check if Umami installation exists
      ansible.builtin.stat:
        path: "{{ umami_install_dir }}/compose.yml"
      register: umami_exists

    - name: Stop and remove Umami containers
      ansible.builtin.command: docker compose down -v
      args:
        chdir: "{{ umami_install_dir }}"
      when: umami_exists.stat.exists
      failed_when: false

    - name: Remove Umami Docker images
      ansible.builtin.command: docker compose down --rmi all
      args:
        chdir: "{{ umami_install_dir }}"
      when: umami_exists.stat.exists
      failed_when: false

    - name: Prompt for data deletion
      ansible.builtin.pause:
        prompt: |

          WARNING: Do you want to delete all Umami data including analytics database?
          This action is irreversible and will delete:
            - All analytics data in {{ umami_data_dir }}
            - PostgreSQL database and volumes
            - Configuration files

          Type 'yes' to confirm data deletion, or 'no' to keep data
      register: delete_data_prompt
      when: umami_exists.stat.exists

    - name: Remove Umami data directory
      ansible.builtin.file:
        path: "{{ umami_data_dir }}"
        state: absent
      when:
        - umami_exists.stat.exists
        - delete_data_prompt.user_input | default('no') | lower == 'yes'

    - name: Remove Umami installation directory
      ansible.builtin.file:
        path: "{{ umami_install_dir }}"
        state: absent
      when: umami_exists.stat.exists

    - name: Display uninstall summary
      ansible.builtin.debug:
        msg:
          - "Umami Web Analytics has been uninstalled!"
          - "=========================================="
          - "Removed:"
          - "  - Docker containers and images"
          - "  - Configuration files"
          - "{{ '  - Analytics data and database' if (delete_data_prompt.user_input | default('no') | lower == 'yes') else '  - Analytics data preserved in ' + umami_data_dir }}"
          - ""
          - "Docker and Docker Compose remain installed for other applications."
          - "To remove Docker completely, run: apt remove docker-ce docker-ce-cli (Debian/Ubuntu)"
          - "                            or: dnf remove docker-ce docker-ce-cli (RHEL 8+/Rocky/Alma)"
      when: umami_exists.stat.exists

    - name: Display message if Umami not found
      ansible.builtin.debug:
        msg: "Umami installation not found at {{ umami_install_dir }}"
      when: not umami_exists.stat.exists
