---
- name: Uninstall n8n Workflow Automation Platform
  hosts: all
  become: true

  vars:
    n8n_data_dir: "/opt/n8n"
    remove_data: false
    remove_docker: false

  pre_tasks:
    - name: Confirm uninstallation
      pause:
        prompt: |
          WARNING: This will remove n8n and all associated services.
          {% if remove_data %}
          ALL DATA WILL BE PERMANENTLY DELETED including workflows, credentials, and database!
          {% else %}
          Data will be preserved in {{ n8n_data_dir }} (set remove_data=true to delete).
          {% endif %}
          {% if remove_docker %}
          Docker will also be removed from the system.
          {% endif %}

          Press ENTER to continue or Ctrl+C to abort.
      when: ansible_check_mode is not defined or not ansible_check_mode

  tasks:
    - name: Stop n8n service
      systemd:
        name: n8n
        state: stopped
      ignore_errors: yes

    - name: Disable n8n service
      systemd:
        name: n8n
        enabled: no
      ignore_errors: yes

    - name: Stop and remove n8n containers
      shell: |
        cd {{ n8n_data_dir }}
        docker compose down -v
      args:
        chdir: "{{ n8n_data_dir }}"
      ignore_errors: yes
      when: n8n_data_dir is exists

    - name: Remove n8n systemd service file
      file:
        path: /etc/systemd/system/n8n.service
        state: absent

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Remove n8n Docker images
      docker_image:
        name: "{{ item }}"
        state: absent
        force_absent: yes
      loop:
        - "n8nio/n8n:1.120.3"
        - "n8nio/n8n:latest"
        - "postgres:16"
        - "postgres:latest"
      ignore_errors: yes

    - name: Remove Caddy image
      shell: |
        docker images | grep "{{ n8n_data_dir | regex_replace('/', '_') }}" | awk '{print $3}' | xargs -r docker rmi -f
      ignore_errors: yes

    - name: Backup credentials before removal
      copy:
        src: "{{ n8n_data_dir }}/credentials.txt"
        dest: "/root/n8n-credentials-backup-{{ ansible_date_time.epoch }}.txt"
        remote_src: yes
      ignore_errors: yes
      when:
        - remove_data
        - n8n_data_dir + '/credentials.txt' is exists

    - name: Remove n8n data directory
      file:
        path: "{{ n8n_data_dir }}"
        state: absent
      when: remove_data

    - name: Remove Docker (if requested)
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: absent
        purge: yes
      when:
        - remove_docker
        - ansible_pkg_mgr == "apt"

    - name: Remove Docker repository
      apt_repository:
        repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: absent
      when:
        - remove_docker
        - ansible_pkg_mgr == "apt"

    - name: Remove Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
        state: absent
      when:
        - remove_docker
        - ansible_pkg_mgr == "apt"

    - name: Remove Docker data directory
      file:
        path: /var/lib/docker
        state: absent
      when: remove_docker

    - name: Display uninstallation summary
      debug:
        msg:
          - "n8n has been uninstalled successfully!"
          - "==================== SUMMARY ================================"
          - "n8n service: Stopped and removed"
          - "Docker containers: Removed"
          - "Docker images: Removed"
          - "{% if remove_data %}Data directory: DELETED ({{ n8n_data_dir }}){% else %}Data directory: PRESERVED ({{ n8n_data_dir }}){% endif %}"
          - "{% if remove_data %}Credentials backup: /root/n8n-credentials-backup-{{ ansible_date_time.epoch }}.txt{% endif %}"
          - "{% if remove_docker %}Docker: Removed from system{% else %}Docker: Kept on system{% endif %}"
          - "============================================================="
          - "{% if not remove_data %}To completely remove all data, run with: remove_data=true{% endif %}"
          - "{% if not remove_docker %}To also remove Docker, run with: remove_docker=true{% endif %}"
